apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'cc.mytree'
version = '0.1.0'

expoModule {
  canBePublished false
}

android {
  namespace 'cc.mytree.linelogin'

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'com.linecorp.linesdk:linesdk:5.12.0'
}
