import { useEffect, useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { getCommunitySafetySnapshot, listMyActiveCommunities, type CommunityRisk, type MyCommunity, type PublicIncident } from "@/lib/communityEmergency";

const INCIDENT_LABEL: Record<string,string> = {
 medical:"ผู้ป่วย / บาดเจ็บ", flood:"น้ำท่วม", fire:"ไฟไหม้", accident:"อุบัติเหตุ",
 "road-obstruction":"ถนน / ทางผ่านไม่ได้","utility-infrastructure":"สาธารณูปโภค / สิ่งกีดขวาง",
 "missing-person":"บุคคลสูญหาย","evacuation-rescue":"อพยพ / กู้ภัย",supplies:"สิ่งของจำเป็น",other:"เหตุอื่น",
};
const RISK_LABEL = { advisory:"เฝ้าระวัง", watch:"จับตา", warning:"เตือน", emergency:"ฉุกเฉิน" } as const;
function ageLabel(value:string) {
 const minutes=Math.max(0,Math.round((Date.now()-new Date(value).getTime())/60000));
 if(minutes<1)return "เมื่อสักครู่"; if(minutes<60)return `${minutes} นาทีที่แล้ว`;
 const hours=Math.round(minutes/60); return hours<24?`${hours} ชม.ที่แล้ว`:`${Math.round(hours/24)} วันที่แล้ว`;
}
function RiskCard({risk}:{risk:CommunityRisk}) {
 return <article className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-amber-800">{risk.provenance==="official"?"ประกาศจากแหล่งทางการ":"MyTree Forecast"}</p><h3 className="mt-1 font-black">{risk.hazard}</h3></div><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-amber-800">{RISK_LABEL[risk.level]}</span></div><p className="mt-2 text-xs text-gray-600">อัปเดต {ageLabel(risk.updated_at)} · ใช้ถึง {new Date(risk.expires_at).toLocaleString("th-TH")}</p>{risk.provenance==="forecast"&&<p className="mt-2 text-xs font-semibold text-amber-900">เป็นการคาดการณ์ ไม่ใช่การยืนยันว่าจะเกิดเหตุ</p>}</article>;
}
function IncidentCard({incident}:{incident:PublicIncident}) {
 return <article className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-[#b42318]">รายงานจากชุมชน</p><h3 className="mt-1 font-black">{INCIDENT_LABEL[incident.category]||incident.category}</h3></div><span className="text-xs text-gray-500">{ageLabel(incident.updated_at)}</span></div>{incident.description&&<p className="mt-2 line-clamp-3 text-sm text-gray-700">{incident.description}</p>}<div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs">{incident.status}</span>{incident.road_impact!=="unknown"&&<span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-semibold text-red-700">ถนน: {incident.road_impact}</span>}</div><p className="mt-3 text-[11px] text-gray-500">ตำแหน่งที่แสดงเป็นระดับ {incident.public_location_precision} และอาจไม่ใช่จุดบ้าน/ผู้ประสบเหตุที่แน่นอน</p></article>;
}
export function CommunityIncidentMap() {
 const [communities,setCommunities]=useState<MyCommunity[]>([]); const [communityId,setCommunityId]=useState("");
 const [incidents,setIncidents]=useState<PublicIncident[]>([]); const [risks,setRisks]=useState<CommunityRisk[]>([]);
 const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{void listMyActiveCommunities().then((items)=>{setCommunities(items);if(items[0])setCommunityId(items[0].community_id);}).catch((e)=>setError(e instanceof Error?e.message:"โหลดชุมชนไม่สำเร็จ")).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!communityId)return;setLoading(true);void getCommunitySafetySnapshot(communityId).then((s)=>{setIncidents(s.incidents);setRisks(s.risks);setError(null);}).catch((e)=>setError(e instanceof Error?e.message:"โหลดเหตุการณ์ไม่สำเร็จ")).finally(()=>setLoading(false));},[communityId]);
 const mapped=useMemo(()=>incidents.filter((i)=>i.public_lat!==null&&i.public_lng!==null),[incidents]);
 return <main className="min-h-dvh bg-[#f8fbf5] pb-24 text-[#173c29]"><header className="border-b bg-white px-4 pb-4 pt-[max(1rem,env(safe-area-inset-top))]"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wide text-[#b42318]">Community Safety</p><h1 className="text-2xl font-black">เหตุการณ์ & การแจ้งเตือน</h1></div><Link to="/community/report" className="rounded-full bg-[#b42318] px-4 py-3 text-sm font-black text-white">⚠️ แจ้งเหตุ</Link></div><select value={communityId} onChange={(e)=>setCommunityId(e.target.value)} className="mt-4 w-full rounded-xl border p-3 text-sm">{communities.map((c)=><option key={c.community_id} value={c.community_id}>{c.name}</option>)}</select></div></header><div className="mx-auto max-w-5xl space-y-4 p-4">{risks.length>0&&<section><h2 className="mb-2 font-black">แจ้งเตือนและความเสี่ยง</h2><div className="grid gap-2 md:grid-cols-2">{risks.map((r)=><RiskCard key={r.risk_id} risk={r}/>)}</div></section>}<section className="relative min-h-[300px] overflow-hidden rounded-3xl border bg-[#eaf2ea] p-5"><div className="absolute inset-0 opacity-40" aria-hidden="true" style={{backgroundImage:"radial-gradient(#668170 1px,transparent 1px)",backgroundSize:"18px 18px"}}/><div className="relative"><h2 className="font-black">Incident Map</h2><p className="mt-1 text-sm text-gray-600">มี {mapped.length} เหตุที่มีตำแหน่งสำหรับแสดงบนแผนที่</p><div className="mt-8 rounded-2xl bg-white/90 p-5 text-sm text-gray-700 shadow"><p className="font-bold">Google basemap integration กำลังเชื่อมกับ Main Map รุ่นล่าสุด</p><p className="mt-2">M3 foundation ตอนนี้อ่านเฉพาะ public-safe coordinates จาก RPC แล้ว ไม่มี exact incident coordinates ใน payload นี้</p></div></div></section><section><div className="mb-2 flex items-center justify-between"><h2 className="font-black">เหตุล่าสุด</h2><span className="text-xs text-gray-500">{incidents.length} เหตุ</span></div>{loading?<div className="rounded-2xl bg-white p-6 text-center text-sm">กำลังโหลด…</div>:error?<div className="rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>:<div className="grid gap-3 md:grid-cols-2">{incidents.map((i)=><IncidentCard key={i.incident_id} incident={i}/>)}</div>}</section></div></main>;
}
