import { useState } from "react";
import { analyzeCommunitySafetyRoutes, type SafetyRouteOption } from "@/lib/communityEmergency";
import { googleDirectionsWithWaypoints } from "@/lib/incidentRouting";

function distanceLabel(m:number){return m<1000?`${Math.round(m)} ม.`:`${(m/1000).toFixed(1)} กม.`;}
function durationLabel(s:number){const m=Math.round(s/60);return m<60?`${m} นาที`:`${Math.floor(m/60)} ชม. ${m%60} นาที`;}
function RouteCard({route,index,onOpen}:{route:SafetyRouteOption;index:number;onOpen:()=>void}) {
 const fresh=route.impacts.filter((i)=>!i.stale), stale=route.impacts.filter((i)=>i.stale);
 return <article className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-[#1f6a45]">เส้นทางวิเคราะห์ {index+1}</p><h3 className="mt-1 font-black">{distanceLabel(route.distanceMeters)} · {durationLabel(route.durationSeconds)}</h3></div><span className={`rounded-full px-3 py-1 text-xs font-black ${route.impactScore===0?"bg-green-50 text-green-700":route.impactScore<80?"bg-amber-50 text-amber-800":"bg-red-50 text-red-700"}`}>Impact {route.impactScore}</span></div>{route.impacts.length===0?<p className="mt-3 rounded-xl bg-green-50 p-3 text-sm text-green-800">ไม่พบรายงานถนน difficult/closed ที่เข้าใกล้เส้นทางนี้จากข้อมูล MyTree ปัจจุบัน — ไม่ได้หมายความว่าเส้นทางปลอดภัย</p>:<div className="mt-3 space-y-2">{fresh.map((impact)=><div key={impact.incidentId} className="rounded-xl bg-red-50 p-3 text-sm"><b>{impact.impact==="closed"?"มีรายงานถนนปิด":"มีรายงานผ่านยาก"}</b><div className="mt-1 text-xs text-gray-600">ห่างแนวเส้นทาง ~{impact.distanceFromRouteMeters} ม. · {impact.verification} · อัปเดต {impact.ageHours} ชม.ก่อน</div></div>)}{stale.map((impact)=><div key={impact.incidentId} className="rounded-xl bg-gray-100 p-3 text-xs text-gray-600">ข้อมูลเก่า: {impact.impact} · {impact.ageHours} ชม.ก่อน — ลดน้ำหนักในการวิเคราะห์แล้ว</div>)}</div>}<button type="button" onClick={onOpen} className="mt-4 w-full rounded-xl bg-[#1f6a45] px-4 py-3 text-sm font-black text-white">เปิด Google Navigation</button></article>;
}
export function SafetyRouteComparison({communityId,destination}:{communityId:string;destination:{lat:number;lng:number}}) {
 const [origin,setOrigin]=useState<{lat:number;lng:number}|null>(null);const [routes,setRoutes]=useState<SafetyRouteOption[]>([]);
 const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);
 function analyze(){setLoading(true);setError(null);navigator.geolocation.getCurrentPosition((p)=>{const o={lat:p.coords.latitude,lng:p.coords.longitude};setOrigin(o);void analyzeCommunitySafetyRoutes(communityId,o,destination).then((r)=>setRoutes(r.routes)).catch((e)=>setError(e instanceof Error?e.message:"วิเคราะห์เส้นทางไม่สำเร็จ")).finally(()=>setLoading(false));},()=>{setError("อ่านตำแหน่งปัจจุบันไม่สำเร็จ");setLoading(false);},{enableHighAccuracy:true,timeout:10000,maximumAge:30000});}
 return <section className="rounded-3xl border bg-[#f8fbf5] p-4"><h2 className="font-black">เส้นทางและจุดที่ควรระวัง</h2><p className="mt-1 text-xs leading-5 text-gray-600">MyTree เปรียบเทียบเส้นทางกับรายงานถนนในชุมชน ข้อมูลนี้ไม่ใช่การรับรองว่าเส้นทางปลอดภัย</p>{routes.length===0&&<button type="button" disabled={loading} onClick={analyze} className="mt-3 w-full rounded-xl bg-[#1f6a45] px-4 py-3 font-black text-white disabled:opacity-50">{loading?"กำลังวิเคราะห์…":"วิเคราะห์เส้นทางจากตำแหน่งฉัน"}</button>}{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{routes.length>0&&<div className="mt-4 grid gap-3">{routes.map((route,index)=><RouteCard key={route.routeIndex} route={route} index={index} onOpen={()=>window.open(googleDirectionsWithWaypoints(destination,origin),"_blank","noopener,noreferrer")}/>)}</div>}{routes.length>0&&<p className="mt-3 text-[11px] leading-5 text-gray-500">เมื่อเปิด Google Navigation ระบบปลายทางอาจคำนวณเส้นทางใหม่ตามสภาพจราจร จึงควรตรวจจุดแจ้งเหตุอีกครั้งก่อนเดินทาง</p>}</section>;
}
