import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import { getAdminAccessContext,hasAdminPermission,type AdminAccessContext } from "@/lib/adminAccess";
import { addMemberNote,decideMemberDeletion,getMember,listMembers,setMemberStatus,updateMemberProfile,type MemberDetail,type MemberListItem,type MemberStatus } from "@/lib/memberAdmin";

const fmt=(v:string|null|undefined)=>v?new Intl.DateTimeFormat("th-TH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const roleLabels:Record<string,string>={customer:"Customer",rider:"Rider",shop_staff:"Shop",community_moderator:"Moderator",platform_admin:"Platform Admin"};

export function MemberManagement(){
 const [access,setAccess]=useState<AdminAccessContext|null>(null),[items,setItems]=useState<MemberListItem[]>([]),[detail,setDetail]=useState<MemberDetail|null>(null);
 const [total,setTotal]=useState(0),[page,setPage]=useState(1),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[role,setRole]=useState(""),[communityId,setCommunityId]=useState(""),[sort,setSort]=useState("created_desc");
 const [selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);
 const canUpdate=!!access&&hasAdminPermission(access,"members.update"),canAction=!!access&&hasAdminPermission(access,"members.action"),canAdmin=!!access&&hasAdminPermission(access,"members.admin");
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await listMembers({search,status,role,communityId,sort,page});setItems(r.items);setTotal(r.total);}catch(e){setError(e instanceof Error?e.message:"โหลดสมาชิกไม่สำเร็จ");}finally{setLoading(false)}},[search,status,role,communityId,sort,page]);
 const loadDetail=useCallback(async(id:string)=>{setDetailLoading(true);setError(null);try{setDetail(await getMember(id));}catch(e){setError(e instanceof Error?e.message:"โหลดรายละเอียดไม่สำเร็จ");}finally{setDetailLoading(false)}},[]);
 useEffect(()=>{void getAdminAccessContext().then(setAccess)},[]); useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>clearTimeout(t)},[load]); useEffect(()=>{selected?void loadDetail(selected):setDetail(null)},[selected,loadDetail]);
 const pages=Math.max(1,Math.ceil(total/20)), roles=useMemo(()=>detail?Object.entries(detail.roles).filter(([,v])=>v).map(([k])=>roleLabels[k]??k):[],[detail]);
 async function mutate(run:()=>Promise<void>){setSaving(true);setError(null);try{await run();await Promise.all([load(),selected?loadDetail(selected):Promise.resolve()]);}catch(e){setError(e instanceof Error?e.message:"ดำเนินการไม่สำเร็จ");}finally{setSaving(false)}}
 async function changeStatus(next:MemberStatus){if(!selected||!detail)return;const reason=prompt(`เหตุผลในการเปลี่ยนสถานะเป็น ${next}`);if(!reason)return;if(next!=="active"&&!confirm("การดำเนินการนี้มีผลต่อบัญชีสมาชิก ยืนยันหรือไม่?"))return;await mutate(()=>setMemberStatus(selected,next,reason));}
 function editProfile(){if(!selected||!detail)return;const name=prompt("ชื่อสมาชิก",detail.member.name??"");if(name===null)return;const phone=prompt("เบอร์โทรศัพท์",detail.member.phone??"");if(phone===null)return;const reason=prompt("เหตุผลการแก้ไข (Audit)");if(!reason)return;void mutate(()=>updateMemberProfile(selected,name,phone,reason));}
 function addNote(){if(!selected)return;const note=prompt("บันทึกภายในสำหรับสมาชิก");if(!note)return;const reason=prompt("เหตุผลการบันทึก (Audit)");if(!reason)return;void mutate(()=>addMemberNote(selected,note,reason));}
 function deletion(decision:"approved"|"rejected"|"deferred"){if(!selected)return;const reason=prompt("เหตุผลการตัดสินคำขอลบข้อมูล");if(!reason)return;if(decision==="approved"&&!confirm("อนุมัติเฉพาะ workflow เท่านั้น ระบบจะไม่ Hard Delete ข้อมูลธุรกรรม ยืนยันหรือไม่?"))return;void mutate(()=>decideMemberDeletion(selected,decision,reason));}
 return <div className="space-y-5">
  <section className="rounded-3xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><p className="text-sm font-medium text-emerald-700">Member Management</p><h2 className="mt-1 text-2xl font-bold">สมาชิก MyTree</h2><p className="mt-1 text-sm text-gray-500">Customer ID เป็น identity anchor; LINE แสดงเฉพาะสถานะการเชื่อมโยง ไม่เปิดเผย token หรือ provider secret</p>
   <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-5">
    <input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="ชื่อ / เบอร์ / Customer ID" className="rounded-xl border px-3 py-2.5 text-sm"/>
    <select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">ทุกสถานะ</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="banned">Banned</option></select>
    <select value={role} onChange={e=>{setRole(e.target.value);setPage(1)}} className="rounded-xl border px-3 py-2.5 text-sm"><option value="">ทุก Role</option><option value="customer">Customer</option><option value="shop">Shop</option><option value="rider">Rider</option><option value="community_moderator">Moderator</option><option value="platform_admin">Platform Admin</option></select>
    <input value={communityId} onChange={e=>{setCommunityId(e.target.value);setPage(1)}} placeholder="Community ID (optional)" className="rounded-xl border px-3 py-2.5 text-sm"/>
    <select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm"><option value="created_desc">สร้างล่าสุด</option><option value="created_asc">สร้างเก่าสุด</option><option value="name_asc">ชื่อ A–Z</option><option value="name_desc">ชื่อ Z–A</option><option value="last_active_desc">ใช้งานล่าสุด</option></select>
   </div>
  </section>
  {error&&<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}<button onClick={()=>void load()} className="ml-3 font-semibold underline">ลองใหม่</button></div>}
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(390px,.65fr)]">
   <section className="overflow-hidden rounded-3xl border bg-white shadow-sm">{loading?<State text="กำลังโหลดสมาชิก..."/>:items.length===0?<State text="ไม่พบสมาชิกตามเงื่อนไข"/>:<div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="sticky left-0 bg-gray-50 px-4 py-3">สมาชิก</th><th className="px-4 py-3">สถานะ</th><th className="px-4 py-3">Roles</th><th className="px-4 py-3">LINE</th><th className="px-4 py-3">สร้างเมื่อ</th><th className="px-4 py-3">ล่าสุด</th></tr></thead><tbody className="divide-y">{items.map(x=><tr key={x.customer_id} onClick={()=>setSelected(x.customer_id)} className={`cursor-pointer hover:bg-gray-50 ${selected===x.customer_id?"bg-emerald-50":""}`}><td className="sticky left-0 bg-inherit px-4 py-4"><p className="font-semibold">{x.name||"ไม่ระบุชื่อ"}</p><p className="text-xs text-gray-500">{x.phone||"ไม่มีเบอร์"}</p><p className="max-w-[220px] truncate text-[11px] text-gray-400">{x.customer_id}</p></td><td className="px-4 py-4"><Badge value={x.status}/></td><td className="px-4 py-4 text-xs text-gray-600">{[x.is_shop_staff&&"Shop",x.is_rider&&"Rider",x.is_community_moderator&&"Moderator",x.is_platform_admin&&"Admin"].filter(Boolean).join(", ")||"Customer"}</td><td className="px-4 py-4">{x.line_linked?"Linked":"—"}</td><td className="px-4 py-4 whitespace-nowrap">{fmt(x.created_at)}</td><td className="px-4 py-4 whitespace-nowrap">{fmt(x.last_active_at)}</td></tr>)}</tbody></table></div>}
    <div className="flex items-center justify-between border-t p-3 text-sm text-gray-500"><span>{total} สมาชิก</span><div className="flex items-center gap-2"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">ก่อนหน้า</button><span>{page}/{pages}</span><button disabled={page>=pages} onClick={()=>setPage(v=>v+1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">ถัดไป</button></div></div>
   </section>
   <aside className="rounded-3xl border bg-white p-5 shadow-sm">{!selected?<State text="เลือกสมาชิกเพื่อดูรายละเอียด"/>:detailLoading||!detail?<State text="กำลังโหลดรายละเอียด..."/>:<div className="space-y-5">
    <div><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-bold">{detail.member.name||"ไม่ระบุชื่อ"}</h3><p className="text-sm text-gray-500">{detail.member.phone||"ไม่มีเบอร์โทร"}</p></div><Badge value={detail.member.status}/></div><p className="mt-2 break-all text-xs text-gray-400">{detail.member.customer_id}</p><p className="mt-1 text-xs text-gray-400">สร้าง {fmt(detail.member.created_at)}</p></div>
    <Block title="Identity & Roles"><p>LINE: <b>{detail.identity.line_linked?"Linked":"Not linked"}</b> · Conflict: {detail.identity.mapping_conflict?"พบ":"ไม่พบ"}</p><p className="mt-1">Providers: {detail.identity.providers.join(", ")||"—"}</p><div className="mt-2 flex flex-wrap gap-1">{roles.map(r=><span key={r} className="rounded-full bg-gray-100 px-2 py-1 text-xs">{r}</span>)}</div></Block>
    <Block title="Activity">{Object.entries(detail.activity).map(([k,v])=><p key={k} className="mt-1 text-sm"><span className="capitalize">{k}</span>: {v.available?(v.count??fmt(v.last_active_at)):"Unavailable"}{v.last_at?` · ล่าสุด ${fmt(v.last_at)}`:""}</p>)}</Block>
    <Block title="Relationships"><p>Communities: {detail.communities.length}</p><p>Shops: {detail.shops.length}</p><p>Rider: {detail.rider?detail.rider.class:"—"}</p></Block>
    <div className="flex flex-wrap gap-2">{canUpdate&&<button onClick={editProfile} className="rounded-xl border px-3 py-2 text-sm font-medium">แก้ Profile</button>}{canAction&&detail.member.status!=="active"&&<button disabled={saving} onClick={()=>void changeStatus("active")} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-medium text-white">Unsuspend / Unban</button>}{canAction&&detail.member.status==="active"&&<button disabled={saving} onClick={()=>void changeStatus("suspended")} className="rounded-xl border border-amber-300 px-3 py-2 text-sm text-amber-700">Suspend</button>}{canAction&&detail.member.status!=="banned"&&<button disabled={saving} onClick={()=>void changeStatus("banned")} className="rounded-xl border border-red-300 px-3 py-2 text-sm text-red-700">Ban</button>}</div>
    {canAdmin&&<Block title="Admin controls"><button onClick={addNote} className="mr-2 rounded-lg border px-2.5 py-1.5 text-xs">+ Note</button><button onClick={()=>deletion("approved")} className="mr-2 rounded-lg border px-2.5 py-1.5 text-xs">Approve deletion</button><button onClick={()=>deletion("rejected")} className="mr-2 rounded-lg border px-2.5 py-1.5 text-xs">Reject</button><button onClick={()=>deletion("deferred")} className="rounded-lg border px-2.5 py-1.5 text-xs">Defer</button><p className="mt-2 text-xs text-gray-500">Hard delete ไม่ทำอัตโนมัติ เพื่อรักษา transaction/history dependency</p></Block>}
    <Block title="Audit history">{detail.audit.length===0?<p>ไม่มีข้อมูลหรือไม่มีสิทธิ์ system.audit.read</p>:detail.audit.slice(0,8).map(a=><div key={a.audit_id} className="border-l-2 pl-3 mt-2"><p className="text-sm font-medium">{a.action}</p><p className="text-xs text-gray-500">{fmt(a.created_at)} · {a.reason||"—"}</p></div>)}</Block>
   </div>}</aside>
  </div>
 </div>
}
function Badge({value}:{value:string}){const cls=value==="active"?"bg-emerald-100 text-emerald-700":value==="suspended"?"bg-amber-100 text-amber-700":"bg-red-100 text-red-700";return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${cls}`}>{value}</span>}
function State({text}:{text:string}){return <div className="p-10 text-center text-sm text-gray-500">{text}</div>}
function Block({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl bg-gray-50 p-4 text-sm text-gray-600"><h4 className="mb-2 font-semibold text-gray-900">{title}</h4>{children}</section>}
