/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityEventsRouteImport } from './routes/community/events'
import { Route as CommunityFeedRouteImport } from './routes/community/feed'
import { Route as CommunityGroupsRouteImport } from './routes/community/groups'
import { Route as CommunityHelpRouteImport } from './routes/community/help'
import { Route as CommunityMapRouteImport } from './routes/community/map'
import { Route as CommunityMarketplaceRouteImport } from './routes/community/marketplace'
import { Route as DebugCheckoutMapRouteImport } from './routes/debug/checkout-map'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as RiderIndexRouteImport } from './routes/rider/index'
import { Route as RiderProfileRouteImport } from './routes/rider/profile'
import { Route as RiderSignupRouteImport } from './routes/rider/signup'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopShopIdRouteImport } from './routes/shop/$shopId'
import { Route as SweetIndexRouteImport } from './routes/sweet/index'
import { Route as SweetAdminRouteImport } from './routes/sweet/admin'
import { Route as SweetMenuRouteImport } from './routes/sweet/menu'
import { Route as SweetOrdersRouteImport } from './routes/sweet/orders'
import { Route as SweetPosRouteImport } from './routes/sweet/pos'
import { Route as SweetRidersRouteImport } from './routes/sweet/riders'
import { Route as SweetShopRouteImport } from './routes/sweet/shop'
import { Route as SweetSignupRouteImport } from './routes/sweet/signup'
import { Route as CommunityEventsEventIdRouteImport } from './routes/community/events_.$eventId'
import { Route as CommunityFeedPostIdRouteImport } from './routes/community/feed_.$postId'
import { Route as CommunityGroupsGroupIdRouteImport } from './routes/community/groups_.$groupId'
import { Route as CommunityHelpRequestIdRouteImport } from './routes/community/help_.$requestId'
import { Route as CommunityMapEntryIdRouteImport } from './routes/community/map_.$entryId'
import { Route as CommunityMarketplaceListingIdRouteImport } from './routes/community/marketplace_.$listingId'
import { Route as ShopOrdersIndexRouteImport } from './routes/shop/orders/index'
import { Route as ShopOrdersSubIdRouteImport } from './routes/shop/orders/$subId'
import { Route as SweetPrintSubIdRouteImport } from './routes/sweet/print/$subId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsRoute = CommunityEventsRouteImport.update({
  id: '/community/events',
  path: '/community/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFeedRoute = CommunityFeedRouteImport.update({
  id: '/community/feed',
  path: '/community/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGroupsRoute = CommunityGroupsRouteImport.update({
  id: '/community/groups',
  path: '/community/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityHelpRoute = CommunityHelpRouteImport.update({
  id: '/community/help',
  path: '/community/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMapRoute = CommunityMapRouteImport.update({
  id: '/community/map',
  path: '/community/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMarketplaceRoute = CommunityMarketplaceRouteImport.update({
  id: '/community/marketplace',
  path: '/community/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugCheckoutMapRoute = DebugCheckoutMapRouteImport.update({
  id: '/debug/checkout-map',
  path: '/debug/checkout-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/rider/',
  path: '/rider/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderProfileRoute = RiderProfileRouteImport.update({
  id: '/rider/profile',
  path: '/rider/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderSignupRoute = RiderSignupRouteImport.update({
  id: '/rider/signup',
  path: '/rider/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopShopIdRoute = ShopShopIdRouteImport.update({
  id: '/shop/$shopId',
  path: '/shop/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetIndexRoute = SweetIndexRouteImport.update({
  id: '/sweet/',
  path: '/sweet/',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetAdminRoute = SweetAdminRouteImport.update({
  id: '/sweet/admin',
  path: '/sweet/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetMenuRoute = SweetMenuRouteImport.update({
  id: '/sweet/menu',
  path: '/sweet/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetOrdersRoute = SweetOrdersRouteImport.update({
  id: '/sweet/orders',
  path: '/sweet/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetPosRoute = SweetPosRouteImport.update({
  id: '/sweet/pos',
  path: '/sweet/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetRidersRoute = SweetRidersRouteImport.update({
  id: '/sweet/riders',
  path: '/sweet/riders',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetShopRoute = SweetShopRouteImport.update({
  id: '/sweet/shop',
  path: '/sweet/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetSignupRoute = SweetSignupRouteImport.update({
  id: '/sweet/signup',
  path: '/sweet/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsEventIdRoute = CommunityEventsEventIdRouteImport.update({
  id: '/community/events_/$eventId',
  path: '/community/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFeedPostIdRoute = CommunityFeedPostIdRouteImport.update({
  id: '/community/feed_/$postId',
  path: '/community/feed/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGroupsGroupIdRoute = CommunityGroupsGroupIdRouteImport.update({
  id: '/community/groups_/$groupId',
  path: '/community/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityHelpRequestIdRoute = CommunityHelpRequestIdRouteImport.update({
  id: '/community/help_/$requestId',
  path: '/community/help/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMapEntryIdRoute = CommunityMapEntryIdRouteImport.update({
  id: '/community/map_/$entryId',
  path: '/community/map/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityMarketplaceListingIdRoute =
  CommunityMarketplaceListingIdRouteImport.update({
    id: '/community/marketplace_/$listingId',
    path: '/community/marketplace/$listingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopOrdersIndexRoute = ShopOrdersIndexRouteImport.update({
  id: '/shop/orders/',
  path: '/shop/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOrdersSubIdRoute = ShopOrdersSubIdRouteImport.update({
  id: '/shop/orders/$subId',
  path: '/shop/orders/$subId',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetPrintSubIdRoute = SweetPrintSubIdRouteImport.update({
  id: '/sweet/print/$subId',
  path: '/sweet/print/$subId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/feed': typeof CommunityFeedRoute
  '/community/groups': typeof CommunityGroupsRoute
  '/community/help': typeof CommunityHelpRoute
  '/community/map': typeof CommunityMapRoute
  '/community/marketplace': typeof CommunityMarketplaceRoute
  '/debug/checkout-map': typeof DebugCheckoutMapRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/signup': typeof RiderSignupRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/sweet/admin': typeof SweetAdminRoute
  '/sweet/menu': typeof SweetMenuRoute
  '/sweet/orders': typeof SweetOrdersRoute
  '/sweet/pos': typeof SweetPosRoute
  '/sweet/riders': typeof SweetRidersRoute
  '/sweet/shop': typeof SweetShopRoute
  '/sweet/signup': typeof SweetSignupRoute
  '/community/': typeof CommunityIndexRoute
  '/hub/': typeof HubIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/sweet/': typeof SweetIndexRoute
  '/community/events/$eventId': typeof CommunityEventsEventIdRoute
  '/community/feed/$postId': typeof CommunityFeedPostIdRoute
  '/community/groups/$groupId': typeof CommunityGroupsGroupIdRoute
  '/community/help/$requestId': typeof CommunityHelpRequestIdRoute
  '/community/map/$entryId': typeof CommunityMapEntryIdRoute
  '/community/marketplace/$listingId': typeof CommunityMarketplaceListingIdRoute
  '/shop/orders/$subId': typeof ShopOrdersSubIdRoute
  '/sweet/print/$subId': typeof SweetPrintSubIdRoute
  '/shop/orders/': typeof ShopOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/feed': typeof CommunityFeedRoute
  '/community/groups': typeof CommunityGroupsRoute
  '/community/help': typeof CommunityHelpRoute
  '/community/map': typeof CommunityMapRoute
  '/community/marketplace': typeof CommunityMarketplaceRoute
  '/debug/checkout-map': typeof DebugCheckoutMapRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/signup': typeof RiderSignupRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/sweet/admin': typeof SweetAdminRoute
  '/sweet/menu': typeof SweetMenuRoute
  '/sweet/orders': typeof SweetOrdersRoute
  '/sweet/pos': typeof SweetPosRoute
  '/sweet/riders': typeof SweetRidersRoute
  '/sweet/shop': typeof SweetShopRoute
  '/sweet/signup': typeof SweetSignupRoute
  '/community': typeof CommunityIndexRoute
  '/hub': typeof HubIndexRoute
  '/rider': typeof RiderIndexRoute
  '/shop': typeof ShopIndexRoute
  '/sweet': typeof SweetIndexRoute
  '/community/events/$eventId': typeof CommunityEventsEventIdRoute
  '/community/feed/$postId': typeof CommunityFeedPostIdRoute
  '/community/groups/$groupId': typeof CommunityGroupsGroupIdRoute
  '/community/help/$requestId': typeof CommunityHelpRequestIdRoute
  '/community/map/$entryId': typeof CommunityMapEntryIdRoute
  '/community/marketplace/$listingId': typeof CommunityMarketplaceListingIdRoute
  '/shop/orders/$subId': typeof ShopOrdersSubIdRoute
  '/sweet/print/$subId': typeof SweetPrintSubIdRoute
  '/shop/orders': typeof ShopOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/feed': typeof CommunityFeedRoute
  '/community/groups': typeof CommunityGroupsRoute
  '/community/help': typeof CommunityHelpRoute
  '/community/map': typeof CommunityMapRoute
  '/community/marketplace': typeof CommunityMarketplaceRoute
  '/debug/checkout-map': typeof DebugCheckoutMapRoute
  '/rider/profile': typeof RiderProfileRoute
  '/rider/signup': typeof RiderSignupRoute
  '/shop/$shopId': typeof ShopShopIdRoute
  '/sweet/admin': typeof SweetAdminRoute
  '/sweet/menu': typeof SweetMenuRoute
  '/sweet/orders': typeof SweetOrdersRoute
  '/sweet/pos': typeof SweetPosRoute
  '/sweet/riders': typeof SweetRidersRoute
  '/sweet/shop': typeof SweetShopRoute
  '/sweet/signup': typeof SweetSignupRoute
  '/community/': typeof CommunityIndexRoute
  '/hub/': typeof HubIndexRoute
  '/rider/': typeof RiderIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/sweet/': typeof SweetIndexRoute
  '/community/events_/$eventId': typeof CommunityEventsEventIdRoute
  '/community/feed_/$postId': typeof CommunityFeedPostIdRoute
  '/community/groups_/$groupId': typeof CommunityGroupsGroupIdRoute
  '/community/help_/$requestId': typeof CommunityHelpRequestIdRoute
  '/community/map_/$entryId': typeof CommunityMapEntryIdRoute
  '/community/marketplace_/$listingId': typeof CommunityMarketplaceListingIdRoute
  '/shop/orders/$subId': typeof ShopOrdersSubIdRoute
  '/sweet/print/$subId': typeof SweetPrintSubIdRoute
  '/shop/orders/': typeof ShopOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/orders'
    | '/community/events'
    | '/community/feed'
    | '/community/groups'
    | '/community/help'
    | '/community/map'
    | '/community/marketplace'
    | '/debug/checkout-map'
    | '/rider/profile'
    | '/rider/signup'
    | '/shop/$shopId'
    | '/sweet/admin'
    | '/sweet/menu'
    | '/sweet/orders'
    | '/sweet/pos'
    | '/sweet/riders'
    | '/sweet/shop'
    | '/sweet/signup'
    | '/community/'
    | '/hub/'
    | '/rider/'
    | '/shop/'
    | '/sweet/'
    | '/community/events/$eventId'
    | '/community/feed/$postId'
    | '/community/groups/$groupId'
    | '/community/help/$requestId'
    | '/community/map/$entryId'
    | '/community/marketplace/$listingId'
    | '/shop/orders/$subId'
    | '/sweet/print/$subId'
    | '/shop/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/orders'
    | '/community/events'
    | '/community/feed'
    | '/community/groups'
    | '/community/help'
    | '/community/map'
    | '/community/marketplace'
    | '/debug/checkout-map'
    | '/rider/profile'
    | '/rider/signup'
    | '/shop/$shopId'
    | '/sweet/admin'
    | '/sweet/menu'
    | '/sweet/orders'
    | '/sweet/pos'
    | '/sweet/riders'
    | '/sweet/shop'
    | '/sweet/signup'
    | '/community'
    | '/hub'
    | '/rider'
    | '/shop'
    | '/sweet'
    | '/community/events/$eventId'
    | '/community/feed/$postId'
    | '/community/groups/$groupId'
    | '/community/help/$requestId'
    | '/community/map/$entryId'
    | '/community/marketplace/$listingId'
    | '/shop/orders/$subId'
    | '/sweet/print/$subId'
    | '/shop/orders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/orders'
    | '/community/events'
    | '/community/feed'
    | '/community/groups'
    | '/community/help'
    | '/community/map'
    | '/community/marketplace'
    | '/debug/checkout-map'
    | '/rider/profile'
    | '/rider/signup'
    | '/shop/$shopId'
    | '/sweet/admin'
    | '/sweet/menu'
    | '/sweet/orders'
    | '/sweet/pos'
    | '/sweet/riders'
    | '/sweet/shop'
    | '/sweet/signup'
    | '/community/'
    | '/hub/'
    | '/rider/'
    | '/shop/'
    | '/sweet/'
    | '/community/events_/$eventId'
    | '/community/feed_/$postId'
    | '/community/groups_/$groupId'
    | '/community/help_/$requestId'
    | '/community/map_/$entryId'
    | '/community/marketplace_/$listingId'
    | '/shop/orders/$subId'
    | '/sweet/print/$subId'
    | '/shop/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  OrdersRoute: typeof OrdersRoute
  CommunityEventsRoute: typeof CommunityEventsRoute
  CommunityFeedRoute: typeof CommunityFeedRoute
  CommunityGroupsRoute: typeof CommunityGroupsRoute
  CommunityHelpRoute: typeof CommunityHelpRoute
  CommunityMapRoute: typeof CommunityMapRoute
  CommunityMarketplaceRoute: typeof CommunityMarketplaceRoute
  DebugCheckoutMapRoute: typeof DebugCheckoutMapRoute
  RiderProfileRoute: typeof RiderProfileRoute
  RiderSignupRoute: typeof RiderSignupRoute
  ShopShopIdRoute: typeof ShopShopIdRoute
  SweetAdminRoute: typeof SweetAdminRoute
  SweetMenuRoute: typeof SweetMenuRoute
  SweetOrdersRoute: typeof SweetOrdersRoute
  SweetPosRoute: typeof SweetPosRoute
  SweetRidersRoute: typeof SweetRidersRoute
  SweetShopRoute: typeof SweetShopRoute
  SweetSignupRoute: typeof SweetSignupRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  HubIndexRoute: typeof HubIndexRoute
  RiderIndexRoute: typeof RiderIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  SweetIndexRoute: typeof SweetIndexRoute
  CommunityEventsEventIdRoute: typeof CommunityEventsEventIdRoute
  CommunityFeedPostIdRoute: typeof CommunityFeedPostIdRoute
  CommunityGroupsGroupIdRoute: typeof CommunityGroupsGroupIdRoute
  CommunityHelpRequestIdRoute: typeof CommunityHelpRequestIdRoute
  CommunityMapEntryIdRoute: typeof CommunityMapEntryIdRoute
  CommunityMarketplaceListingIdRoute: typeof CommunityMarketplaceListingIdRoute
  ShopOrdersSubIdRoute: typeof ShopOrdersSubIdRoute
  SweetPrintSubIdRoute: typeof SweetPrintSubIdRoute
  ShopOrdersIndexRoute: typeof ShopOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/events': {
      id: '/community/events'
      path: '/community/events'
      fullPath: '/community/events'
      preLoaderRoute: typeof CommunityEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/feed': {
      id: '/community/feed'
      path: '/community/feed'
      fullPath: '/community/feed'
      preLoaderRoute: typeof CommunityFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/groups': {
      id: '/community/groups'
      path: '/community/groups'
      fullPath: '/community/groups'
      preLoaderRoute: typeof CommunityGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/help': {
      id: '/community/help'
      path: '/community/help'
      fullPath: '/community/help'
      preLoaderRoute: typeof CommunityHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/map': {
      id: '/community/map'
      path: '/community/map'
      fullPath: '/community/map'
      preLoaderRoute: typeof CommunityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/marketplace': {
      id: '/community/marketplace'
      path: '/community/marketplace'
      fullPath: '/community/marketplace'
      preLoaderRoute: typeof CommunityMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/checkout-map': {
      id: '/debug/checkout-map'
      path: '/debug/checkout-map'
      fullPath: '/debug/checkout-map'
      preLoaderRoute: typeof DebugCheckoutMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/rider'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/profile': {
      id: '/rider/profile'
      path: '/rider/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof RiderProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/signup': {
      id: '/rider/signup'
      path: '/rider/signup'
      fullPath: '/rider/signup'
      preLoaderRoute: typeof RiderSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$shopId': {
      id: '/shop/$shopId'
      path: '/shop/$shopId'
      fullPath: '/shop/$shopId'
      preLoaderRoute: typeof ShopShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/': {
      id: '/sweet/'
      path: '/sweet'
      fullPath: '/sweet/'
      preLoaderRoute: typeof SweetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/admin': {
      id: '/sweet/admin'
      path: '/sweet/admin'
      fullPath: '/sweet/admin'
      preLoaderRoute: typeof SweetAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/menu': {
      id: '/sweet/menu'
      path: '/sweet/menu'
      fullPath: '/sweet/menu'
      preLoaderRoute: typeof SweetMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/orders': {
      id: '/sweet/orders'
      path: '/sweet/orders'
      fullPath: '/sweet/orders'
      preLoaderRoute: typeof SweetOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/pos': {
      id: '/sweet/pos'
      path: '/sweet/pos'
      fullPath: '/sweet/pos'
      preLoaderRoute: typeof SweetPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/riders': {
      id: '/sweet/riders'
      path: '/sweet/riders'
      fullPath: '/sweet/riders'
      preLoaderRoute: typeof SweetRidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/shop': {
      id: '/sweet/shop'
      path: '/sweet/shop'
      fullPath: '/sweet/shop'
      preLoaderRoute: typeof SweetShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/signup': {
      id: '/sweet/signup'
      path: '/sweet/signup'
      fullPath: '/sweet/signup'
      preLoaderRoute: typeof SweetSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/events_/$eventId': {
      id: '/community/events_/$eventId'
      path: '/community/events/$eventId'
      fullPath: '/community/events/$eventId'
      preLoaderRoute: typeof CommunityEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/feed_/$postId': {
      id: '/community/feed_/$postId'
      path: '/community/feed/$postId'
      fullPath: '/community/feed/$postId'
      preLoaderRoute: typeof CommunityFeedPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/groups_/$groupId': {
      id: '/community/groups_/$groupId'
      path: '/community/groups/$groupId'
      fullPath: '/community/groups/$groupId'
      preLoaderRoute: typeof CommunityGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/help_/$requestId': {
      id: '/community/help_/$requestId'
      path: '/community/help/$requestId'
      fullPath: '/community/help/$requestId'
      preLoaderRoute: typeof CommunityHelpRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/map_/$entryId': {
      id: '/community/map_/$entryId'
      path: '/community/map/$entryId'
      fullPath: '/community/map/$entryId'
      preLoaderRoute: typeof CommunityMapEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/marketplace_/$listingId': {
      id: '/community/marketplace_/$listingId'
      path: '/community/marketplace/$listingId'
      fullPath: '/community/marketplace/$listingId'
      preLoaderRoute: typeof CommunityMarketplaceListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/orders/': {
      id: '/shop/orders/'
      path: '/shop/orders'
      fullPath: '/shop/orders/'
      preLoaderRoute: typeof ShopOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/orders/$subId': {
      id: '/shop/orders/$subId'
      path: '/shop/orders/$subId'
      fullPath: '/shop/orders/$subId'
      preLoaderRoute: typeof ShopOrdersSubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/print/$subId': {
      id: '/sweet/print/$subId'
      path: '/sweet/print/$subId'
      fullPath: '/sweet/print/$subId'
      preLoaderRoute: typeof SweetPrintSubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  OrdersRoute: OrdersRoute,
  CommunityEventsRoute: CommunityEventsRoute,
  CommunityFeedRoute: CommunityFeedRoute,
  CommunityGroupsRoute: CommunityGroupsRoute,
  CommunityHelpRoute: CommunityHelpRoute,
  CommunityMapRoute: CommunityMapRoute,
  CommunityMarketplaceRoute: CommunityMarketplaceRoute,
  DebugCheckoutMapRoute: DebugCheckoutMapRoute,
  RiderProfileRoute: RiderProfileRoute,
  RiderSignupRoute: RiderSignupRoute,
  ShopShopIdRoute: ShopShopIdRoute,
  SweetAdminRoute: SweetAdminRoute,
  SweetMenuRoute: SweetMenuRoute,
  SweetOrdersRoute: SweetOrdersRoute,
  SweetPosRoute: SweetPosRoute,
  SweetRidersRoute: SweetRidersRoute,
  SweetShopRoute: SweetShopRoute,
  SweetSignupRoute: SweetSignupRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  HubIndexRoute: HubIndexRoute,
  RiderIndexRoute: RiderIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  SweetIndexRoute: SweetIndexRoute,
  CommunityEventsEventIdRoute: CommunityEventsEventIdRoute,
  CommunityFeedPostIdRoute: CommunityFeedPostIdRoute,
  CommunityGroupsGroupIdRoute: CommunityGroupsGroupIdRoute,
  CommunityHelpRequestIdRoute: CommunityHelpRequestIdRoute,
  CommunityMapEntryIdRoute: CommunityMapEntryIdRoute,
  CommunityMarketplaceListingIdRoute: CommunityMarketplaceListingIdRoute,
  ShopOrdersSubIdRoute: ShopOrdersSubIdRoute,
  SweetPrintSubIdRoute: SweetPrintSubIdRoute,
  ShopOrdersIndexRoute: ShopOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
