/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SweetIndexRouteImport } from './routes/sweet/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as HubIndexRouteImport } from './routes/hub/index'
import { Route as ShopOrdersIndexRouteImport } from './routes/shop/orders/index'
import { Route as ShopOrdersSubIdRouteImport } from './routes/shop/orders/$subId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetIndexRoute = SweetIndexRouteImport.update({
  id: '/sweet/',
  path: '/sweet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOrdersIndexRoute = ShopOrdersIndexRouteImport.update({
  id: '/shop/orders/',
  path: '/shop/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOrdersSubIdRoute = ShopOrdersSubIdRouteImport.update({
  id: '/shop/orders/$subId',
  path: '/shop/orders/$subId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hub/': typeof HubIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/sweet/': typeof SweetIndexRoute
  '/shop/orders/$subId': typeof ShopOrdersSubIdRoute
  '/shop/orders/': typeof ShopOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hub': typeof HubIndexRoute
  '/shop': typeof ShopIndexRoute
  '/sweet': typeof SweetIndexRoute
  '/shop/orders/$subId': typeof ShopOrdersSubIdRoute
  '/shop/orders': typeof ShopOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hub/': typeof HubIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/sweet/': typeof SweetIndexRoute
  '/shop/orders/$subId': typeof ShopOrdersSubIdRoute
  '/shop/orders/': typeof ShopOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hub/'
    | '/shop/'
    | '/sweet/'
    | '/shop/orders/$subId'
    | '/shop/orders/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hub' | '/shop' | '/sweet' | '/shop/orders/$subId' | '/shop/orders'
  id:
    | '__root__'
    | '/'
    | '/hub/'
    | '/shop/'
    | '/sweet/'
    | '/shop/orders/$subId'
    | '/shop/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubIndexRoute: typeof HubIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  SweetIndexRoute: typeof SweetIndexRoute
  ShopOrdersSubIdRoute: typeof ShopOrdersSubIdRoute
  ShopOrdersIndexRoute: typeof ShopOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet/': {
      id: '/sweet/'
      path: '/sweet'
      fullPath: '/sweet/'
      preLoaderRoute: typeof SweetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/orders/': {
      id: '/shop/orders/'
      path: '/shop/orders'
      fullPath: '/shop/orders/'
      preLoaderRoute: typeof ShopOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/orders/$subId': {
      id: '/shop/orders/$subId'
      path: '/shop/orders/$subId'
      fullPath: '/shop/orders/$subId'
      preLoaderRoute: typeof ShopOrdersSubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubIndexRoute: HubIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  SweetIndexRoute: SweetIndexRoute,
  ShopOrdersSubIdRoute: ShopOrdersSubIdRoute,
  ShopOrdersIndexRoute: ShopOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
