apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module-gradle-plugin'

group = 'cc.mytree.shop.linelogin'
version = '0.1.0'

android {
  namespace 'cc.mytree.shop.linelogin'
  defaultConfig {
    minSdkVersion 24
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'com.linecorp.linesdk:linesdk:latest.release'
}
